In [86]:
import numpy as np
import torch
import csv
import pandas as pd

In [87]:
wine_path = "data/winedata.csv"

In [88]:
wine_pd =  pd.read_csv(wine_path, sep = ';',dtype= float,skiprows=1)
wine_pd

7  0.27  0.36  20.7  0.045    45    170    1.001     3  0.45   8.8  \
0     6.3  0.30  0.34   1.6  0.049  14.0  132.0  0.99400  3.30  0.49   9.5   
1     8.1  0.28  0.40   6.9  0.050  30.0   97.0  0.99510  3.26  0.44  10.1   
2     7.2  0.23  0.32   8.5  0.058  47.0  186.0  0.99560  3.19  0.40   9.9   
3     7.2  0.23  0.32   8.5  0.058  47.0  186.0  0.99560  3.19  0.40   9.9   
4     8.1  0.28  0.40   6.9  0.050  30.0   97.0  0.99510  3.26  0.44  10.1   
...   ...   ...   ...   ...    ...   ...    ...      ...   ...   ...   ...   
4892  6.2  0.21  0.29   1.6  0.039  24.0   92.0  0.99114  3.27  0.50  11.2   
4893  6.6  0.32  0.36   8.0  0.047  57.0  168.0  0.99490  3.15  0.46   9.6   
4894  6.5  0.24  0.19   1.2  0.041  30.0  111.0  0.99254  2.99  0.46   9.4   
4895  5.5  0.29  0.30   1.1  0.022  20.0  110.0  0.98869  3.34  0.38  12.8   
4896  6.0  0.21  0.38   0.8  0.020  22.0   98.0  0.98941  3.26  0.32  11.8   

        6  
0     6.0  
1     6.0  
2     6.0  
3     6.0  
4     6.0  
...   ...  
4892  6.0  
4893  5.0  
4894  6.0  
4895  7.0  
4896  6.0  

[4897 rows x 12 columns]

In [89]:
type(wine_pd)
wine_tensor = torch.tensor(wine_pd.values)
wine_tensor

tensor([[ 6.3000,  0.3000,  0.3400,  ...,  0.4900,  9.5000,  6.0000],
        [ 8.1000,  0.2800,  0.4000,  ...,  0.4400, 10.1000,  6.0000],
        [ 7.2000,  0.2300,  0.3200,  ...,  0.4000,  9.9000,  6.0000],
        ...,
        [ 6.5000,  0.2400,  0.1900,  ...,  0.4600,  9.4000,  6.0000],
        [ 5.5000,  0.2900,  0.3000,  ...,  0.3800, 12.8000,  7.0000],
        [ 6.0000,  0.2100,  0.3800,  ...,  0.3200, 11.8000,  6.0000]],
       dtype=torch.float64)

In [90]:
type(wine_tensor)

torch.Tensor

In [91]:
data = wine_tensor[:,:-1]
data

tensor([[ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
        [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
        [ 7.2000,  0.2300,  0.3200,  ...,  3.1900,  0.4000,  9.9000],
        ...,
        [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
        [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
        [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]],
       dtype=torch.float64)

In [92]:
target = wine_tensor[:,-1].long()
target

tensor([6, 6, 6,  ..., 6, 7, 6])

In [93]:
target.shape
target.unique()
target.shape[0]

4897

In [94]:
target_onehot = torch.zeros(target.shape[0],10)
target_onehot.shape

torch.Size([4897, 10])

In [96]:
result = target_onehot.scatter_(1, target.unsqueeze(1), 1.0)
result

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])